### ISSUE TITLE
Opening two projects in two windows results in infinite loop of reloading

### ISSUE THREAD

**Issue by aechan** [loiane/ionic-extension-pack-vsce#2]
From: https://github.com/Microsoft/vscode/issues/63058

VSCode Version: 1.29.0
OS Version: macOS 10.14
Steps to Reproduce:

Open a project in one window with File -> New Window, File -> Open Recent
Open a project in another window with the same steps.
Does this issue occur when all extensions are disabled?: NO

One of the projects was an Ionic project and the bug seems to stop when I disable this extension.

Video of the bug occurring here

--------

This extension seems to be causing the problem shown in the video. Looking for any insights on this bug.

**Comment by loiane** [comment]
Closing as it's been two years this issue is open.
